@build:
	mvn package

@run: build
	java -cp target/template-maven-1.0-SNAPSHOT.jar org.example.Main

@watch:
	# watchexec -c -e java -r -- just run
    just build
    clear
    gow -s -e java -g just run
