# PROJECT_NAME := "CppProject"
PROJECT_NAME := shell("basename $(pwd)")

@clean:
    rm -rf .cache build .idea cmake-build-debug

@setup:
    mkdir -p build
    cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Debug > /dev/null 2>&1
    cd build && ninja

@build:
    cmake --build build

@run: build
    ./build/bin/{{PROJECT_NAME}}

@watch:
    # watchexec -c -e cpp,hpp -r -- just run
    just setup 
    clear
    gow -s -e cpp,hpp -g just run

@release:
    mkdir -p build
    cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release > /dev/null 2>&1
    cd build && ninja
    just build
